CRITICAL - 2022-07-18 21:48:11 --> Call to undefined method App\Models\UserModel::logActivationAttempt
#0 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(345): CodeIgniter\Model->__call('logActivationAt...', Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->activateAccount()
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#6 {main}
CRITICAL - 2022-07-18 21:48:39 --> Call to undefined method App\Models\UserModel::logActivationAttempt
#0 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(345): CodeIgniter\Model->__call('logActivationAt...', Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->activateAccount()
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#6 {main}
ERROR - 2022-07-18 21:48:48 --> Unknown column 'username' in 'where clause'
CRITICAL - 2022-07-18 21:48:48 --> Unknown column 'username' in 'where clause'
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(393): CodeIgniter\BaseModel->first()
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->resendActivateAccount()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:50:01 --> login route cannot be found while reverse-routing.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Helpers/url_helper.php(538): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute('login')
#1 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Views/login.php(14): url_to('login')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#5 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(412): view('Myth\\Auth\\Views...', Array)
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:56:04 --> Undefined index: login
#0 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Config/Routes.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', '/Users/mac/Work...', 17, Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(607): CodeIgniter\Router\RouteCollection::Myth\Auth\Config\{closure}(Object(CodeIgniter\Router\RouteCollection))
#2 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Config/Routes.php(34): CodeIgniter\Router\RouteCollection->group('', Array, Object(Closure))
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(354): include('/Users/mac/Work...')
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(426): CodeIgniter\Router\RouteCollection->discoverRoutes()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/Router.php(351): CodeIgniter\Router\RouteCollection->getRoutes('get')
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/Router.php(154): CodeIgniter\Router\Router->checkRoutes('/')
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(726): CodeIgniter\Router\Router->handle('/')
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:56:07 --> Undefined index: login
#0 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Config/Routes.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', '/Users/mac/Work...', 17, Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(607): CodeIgniter\Router\RouteCollection::Myth\Auth\Config\{closure}(Object(CodeIgniter\Router\RouteCollection))
#2 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Config/Routes.php(34): CodeIgniter\Router\RouteCollection->group('', Array, Object(Closure))
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(354): include('/Users/mac/Work...')
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(426): CodeIgniter\Router\RouteCollection->discoverRoutes()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/Router.php(351): CodeIgniter\Router\RouteCollection->getRoutes('get')
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/Router.php(154): CodeIgniter\Router\Router->checkRoutes('logins')
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(726): CodeIgniter\Router\Router->handle('logins')
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:56:11 --> Undefined index: login
#0 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Config/Routes.php(17): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', '/Users/mac/Work...', 17, Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(607): CodeIgniter\Router\RouteCollection::Myth\Auth\Config\{closure}(Object(CodeIgniter\Router\RouteCollection))
#2 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Config/Routes.php(34): CodeIgniter\Router\RouteCollection->group('', Array, Object(Closure))
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(354): include('/Users/mac/Work...')
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/RouteCollection.php(426): CodeIgniter\Router\RouteCollection->discoverRoutes()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/Router.php(351): CodeIgniter\Router\RouteCollection->getRoutes('get')
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Router/Router.php(154): CodeIgniter\Router\Router->checkRoutes('login')
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(726): CodeIgniter\Router\Router->handle('login')
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:56:18 --> login route cannot be found while reverse-routing.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Helpers/url_helper.php(538): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute('login')
#1 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Views/login.php(14): url_to('login')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#5 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(412): view('Myth\\Auth\\Views...', Array)
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:56:22 --> login route cannot be found while reverse-routing.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Helpers/url_helper.php(538): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute('login')
#1 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Views/login.php(14): url_to('login')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#5 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(412): view('Myth\\Auth\\Views...', Array)
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:56:32 --> login route cannot be found while reverse-routing.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Helpers/url_helper.php(538): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute('login')
#1 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Views/login.php(14): url_to('login')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#5 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(412): view('Myth\\Auth\\Views...', Array)
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 21:58:32 --> login route cannot be found while reverse-routing.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Helpers/url_helper.php(538): CodeIgniter\Router\Exceptions\RouterException::forInvalidRoute('login')
#1 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Views/login.php(14): url_to('login')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('Myth\\Auth\\Views...', Array, true)
#5 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(412): view('Myth\\Auth\\Views...', Array)
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(58): Myth\Auth\Controllers\AuthController->_render('Myth\\Auth\\Views...', Array)
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->login()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#12 {main}
CRITICAL - 2022-07-18 22:00:11 --> Undefined variable: route
#0 /Users/mac/Work/Web/new-intranet/app/Config/Routes.php(159): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', '/Users/mac/Work...', 159, Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(713): require('/Users/mac/Work...')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(368): CodeIgniter\CodeIgniter->tryToRouteIt(Object(CodeIgniter\Router\RouteCollection))
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#4 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#6 {main}
CRITICAL - 2022-07-18 22:37:44 --> Undefined variable: config
#0 /Users/mac/Work/Web/new-intranet/app/Views/auth/login.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', '/Users/mac/Work...', 14, Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('auth/login', Array, true)
#4 /Users/mac/Work/Web/new-intranet/app/Controllers/Home.php(29): view('auth/login', Array)
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): App\Controllers\Home->login()
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#10 {main}
CRITICAL - 2022-07-18 22:38:27 --> Undefined variable: config
#0 /Users/mac/Work/Web/new-intranet/app/Views/auth/login.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', '/Users/mac/Work...', 14, Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('auth/login', Array, true)
#4 /Users/mac/Work/Web/new-intranet/app/Controllers/Home.php(29): view('auth/login', Array)
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): App\Controllers\Home->login()
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#10 {main}
ERROR - 2022-07-18 22:38:46 --> Unknown column 'username' in 'where clause'
CRITICAL - 2022-07-18 22:38:46 --> Unknown column 'username' in 'where clause'
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#13 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#14 {main}
CRITICAL - 2022-07-18 22:39:05 --> Undefined variable: config
#0 /Users/mac/Work/Web/new-intranet/app/Views/auth/login.php(14): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', '/Users/mac/Work...', 14, Array)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(210): include('/Users/mac/Work...')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/View/View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Common.php(1089): CodeIgniter\View\View->render('auth/login', Array, true)
#4 /Users/mac/Work/Web/new-intranet/app/Controllers/Home.php(29): view('auth/login', Array)
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): App\Controllers\Home->login()
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#10 {main}
ERROR - 2022-07-18 22:43:00 --> Unknown column 'username' in 'where clause'
CRITICAL - 2022-07-18 22:43:00 --> Unknown column 'username' in 'where clause'
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(292): mysqli->query('SELECT *\nFROM `...', 0)
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT *\nFROM `...')
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT *\nFROM `...')
#3 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1455): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(210): CodeIgniter\Database\BaseBuilder->get()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(622): CodeIgniter\Model->doFirst()
#6 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(140): CodeIgniter\BaseModel->first()
#7 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Authentication/LocalAuthenticator.php(19): Myth\Auth\Authentication\LocalAuthenticator->validate(Array, true)
#8 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(87): Myth\Auth\Authentication\LocalAuthenticator->attempt(Array, false)
#9 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptLogin()
#10 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#11 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#13 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#14 {main}
CRITICAL - 2022-07-18 23:41:52 --> There is no data to insert.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#9 {main}
CRITICAL - 2022-07-18 23:42:37 --> There is no data to insert.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#9 {main}
CRITICAL - 2022-07-18 23:46:34 --> There is no data to insert.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#9 {main}
CRITICAL - 2022-07-18 23:49:43 --> There is no data to insert.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#9 {main}
CRITICAL - 2022-07-18 23:50:03 --> There is no data to insert.
#0 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(718): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Model.php(625): CodeIgniter\BaseModel->insert(Array, false)
#2 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/BaseModel.php(658): CodeIgniter\Model->insert(Object(Myth\Auth\Entities\User), false)
#3 /Users/mac/Work/Web/new-intranet/vendor/myth/auth/src/Controllers/AuthController.php(179): CodeIgniter\BaseModel->save(Object(Myth\Auth\Entities\User))
#4 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(832): Myth\Auth\Controllers\AuthController->attemptRegister()
#5 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(Myth\Auth\Controllers\AuthController))
#6 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 /Users/mac/Work/Web/new-intranet/public/index.php(37): CodeIgniter\CodeIgniter->run()
#8 /Users/mac/Work/Web/new-intranet/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(43): require_once('/Users/mac/Work...')
#9 {main}
